### ISSUE TITLE
Theano backend?

### ISSUE THREAD

**Issue by beeva-ricardoguerrero** [szilard/benchm-dl#2]
Hi, I found your analysis very interesting. May I suggest to complete the section "GPU vs CPU" using Theano backend? I heard that for CPU, Theano is faster than Tensorflow.

**Comment by szilard** [comment]
You can easily run it yourself and see, but there is no much point in using CPUs for conv-nets.

**Comment by beeva-ricardoguerrero** [comment]
Mmm.. yeah, I agree. It was just curiosity.
Thanks
